name: Cleanup Cloud Resources
on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  eks-cleanup:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
        AWS_REGION: us-east-2
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Cleanup EKS resources
        run: |
          ./tools/cloud-providers/aks/cleanup.sh ${{ env.AWS_REGION }}
